const DEFAULT_GAME_SETTINGS = {
  startingFaith: 10,
  divinity2FaithThreshold: 25,
  winFollowers: 10,
  loseFiendFollowers: 8,
  tickMs: 1500,

  world: {
    initialAnimals: 18,
    initialMonsters: 2,
    forestChance: 16,
    wildFruitChance: 6,
    startingGroveFruitChance: 70,
    startingFruitFoodMin: 2,
    startingFruitFoodMax: 6,
  },

  tribes: {
    minimumMembers: 5,
    formationRadius: 4,
    stayRadius: 5,
    returnRadius: 7,
    deterrencePerMember: 8,
    fiendTribeAttraction: 12,
    spawnCooldownDays: 12,
    spawnChance: 20,
    maxMembers: 12,
    foodNeededNearby: 4,
  },

  people: {
    startingFaithMin: 0,
    startingFaithMax: 18,
    startingRotMin: 0,
    startingRotMax: 10,
    startingHungerMin: 28,
    startingHungerMax: 66,
    startingHealthMin: 70,
    startingHealthMax: 100,
    startingFearMin: 0,
    startingFearMax: 20,
    playerFaithThreshold: 50,
    playerFaithRotMargin: 10,
    fiendRotThreshold: 50,
    fiendRotFaithMargin: 0,
    neutralFaithThreshold: 35,
    neutralRotThreshold: 35,
    hungerGainMin: 6,
    hungerGainMax: 10,
    hungerSearchThreshold: 50,
    starvationThreshold: 86,
    starvationDamageMin: 6,
    starvationDamageMax: 12,
    starvationFaithLoss: 4,
    starvationRotGain: 2,
    rotTerrainGain: 2,
    sicknessDamageChance: 28,
    sicknessDamageMin: 3,
    sicknessDamageMax: 7,
    restHealthThreshold: 52,
    restHealthMin: 3,
    restHealthMax: 7,
  },

  player: {
    prayerChance: 28,
    sacrificeChance: 10,
    sacrificeFaithMin: 3,
    sacrificeFaithMax: 6,
    deathWitnessFaithLoss: 5,
    deathWitnessFearGain: 16,
  },

  fiend: {
    startingFaith: 8,
    startingCooldown: 2,
    cooldownMin: 3,
    cooldownMax: 5,
    rotSpreadChance: 100,
    devourChance: 45,
    eatCooldownDays: 4,
    ownTribeDevourChance: 3,
    devourFaithFromFollower: 1,
    devourFaithFromOther: 3,
    animalDevourFaith: 1,
    spoilAttempts: 10,
    spoilRadius: 5,
    spoilFoodMin: 1,
    spoilFoodMax: 3,
    spoilRotGain: 4,
    whisperVictims: 4,
    whisperRotMin: 8,
    whisperRotMax: 14,
    rotBlessingGain: 16,
    rotBlessingHealthGain: 12,
    cultPrayerChance: 24,
  },

  animals: {
    wanderChance: 70,
  },

  monsters: {
    detectionRange: 7,
    attackDamageMin: 22,
    attackDamageMax: 38,
    attackFearGain: 28,
    attackFaithLoss: 6,
  },

  events: {
    firstEventDay: 4,
    intervalDays: 6,
    chance: 55,
    droughtCost: 7,
    droughtFoodLossChance: 35,
    sicknessCost: 9,
    sicknessDuration: 6,
    beastCost: 8,
    rotBloomCost: 10,
    rotBloomRadius: 5,
    rotBloomStrength: 5,
    badOmenCost: 6,
    badOmenFaithLoss: 6,
    badOmenAnswerFaithGain: 8,
  },

  miracles: {
    defaultTargetX: 13,
    defaultTargetY: 10,
    growFruitCost: 3,
    growFruitPatches: 8,
    growFruitFaithGain: 8,
    growFruitRadius: 6,
    blessVitalityCost: 5,
    blessHealthGain: 35,
    blessHungerReduction: 12,
    blessRotReduction: 14,
    blessTicks: 5,
    blessFaithGain: 20,
    sweetScentCost: 4,
    sweetScentTicks: 4,
    sweetScentFaithGain: 5,
    sweetScentFruitFaithGain: 8,
    fruitFaithGain: 3,
    greatHarvestCost: 12,
    greatHarvestPatches: 28,
    greatHarvestFaithGain: 10,
    cleanseRotCost: 8,
    cleanseRadius: 6,
    cleanseRotReduction: 24,
    cleanseFearReduction: 0,
    cleanseFaithGain: 0,
    driveBeastCost: 10,
    lightningFiendCost: 50,
  },
};
